livy.server.host = 0.0.0.0
livy.server.port = 8998
livy.spark.master = spark://spark-master:7077
livy.spark.deploy-mode = client
livy.file.local-dir-whitelist = /opt/spark/notebooks,/opt/spark/pipelines
livy.repl.enable-hive-context = false
livy.server.session.timeout = 1h
livy.spark.spark.pyspark.python=python3.11