# =============================================================================
# databricks.tf — Azure Databricks Workspace
# =============================================================================
# SPEC: Managed Spark, job cluster auto-create/destroy
# DAG uses DatabricksSubmitRunOperator → job cluster per run
# Workspace provides: Spark runtime, DBFS, cluster management, UI
# =============================================================================

resource "azurerm_databricks_workspace" "giljobi" {
  name                = "giljobi-databricks"
  location            = azurerm_resource_group.giljobi.location
  resource_group_name = azurerm_resource_group.giljobi.name
  sku                 = "standard"

  tags = {
    project = "giljobi"
    role    = "spark"
  }
}

# =============================================================================
# Databricks PAT Token — for Airflow DatabricksSubmitRunOperator
# =============================================================================
# Auto-generated via databricks provider (no manual UI login needed).
# Expires in 7 days (matches demo window).
# Passed to Airflow via AIRFLOW_CONN_DATABRICKS_DEFAULT env var.
# =============================================================================
resource "databricks_token" "airflow" {
  comment          = "Airflow DAG access — auto-generated by Terraform"
  lifetime_seconds = 604800 # 7 days

  depends_on = [azurerm_databricks_workspace.giljobi]
}
